"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class LcmPointCloud(object):
    __slots__ = ["numPtdCld", "ptdCld"]

    def __init__(self):
        self.numPtdCld = 0
        self.ptdCld = []

    def encode(self):
        buf = BytesIO()
        buf.write(LcmPointCloud._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.numPtdCld))
        for i0 in range(self.numPtdCld):
            buf.write(struct.pack('>3f', *self.ptdCld[i0][:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LcmPointCloud._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LcmPointCloud._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LcmPointCloud()
        self.numPtdCld = struct.unpack(">q", buf.read(8))[0]
        self.ptdCld = []
        for i0 in range(self.numPtdCld):
            self.ptdCld.append(struct.unpack('>3f', buf.read(12)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if LcmPointCloud in parents: return 0
        tmphash = (0x781f0867ec7d2a2f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LcmPointCloud._packed_fingerprint is None:
            LcmPointCloud._packed_fingerprint = struct.pack(">Q", LcmPointCloud._get_hash_recursive([]))
        return LcmPointCloud._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

